### ISSUE TITLE
fix hotel listing and buttons on mobile

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hotel-explorer#5]
![screenshot_20180905-114411](https://user-images.githubusercontent.com/375483/45087823-7de75480-b107-11e8-8341-0493fbb71dbd.png)

**Comment by skkr** [comment]
On it.

**Comment by skkr** [comment]
Removed the map button to keep the style consistent with the design ref. and because I don't think it adds much value since both buttons loaded the same page, but it can be added back if necessary, maybe in a different way.

![image](https://user-images.githubusercontent.com/1435069/45229994-d18ba680-b29d-11e8-9733-d316d3cc0085.png)
